# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
issuesSections:
  - title: PSSA
    filters: is:open repo:PowerShell/PSScriptAnalyzer
  - title: PlatyPS
    filters: is:open repo:PowerShell/platyPS
  - title: PSResourceGet
    filters: is:open repo:PowerShell/PSResourceGet
  - title: PSReadLine
    filters: is:open repo:PowerShell/PSReadLine
  - title: DSC-Samples
    filters: is:open repo:PowerShell/DSC-Samples
  - title: Crescendo
    filters: is:open repo:PowerShell/Crescendo
prSections:
  - title: PSSA
    filters: is:open repo:PowerShell/PSScriptAnalyzer
  - title: PlatyPS
    filters: is:open repo:PowerShell/platyPS
  - title: PSResourceGet
    filters: is:open repo:PowerShell/PSResourceGet
  - title: PSReadLine
    filters: is:open repo:PowerShell/PSReadLine
  - title: DSC-Samples
    filters: is:open repo:PowerShell/DSC-Samples
  - title: Crescendo
    filters: is:open repo:PowerShell/Crescendo
defaults:
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: true
    width: 60
  layout:
    prs:
      repo:
        hidden: true
      title:
        grow: true
    issues:
      repo:
        hidden: true
      title:
        grow: true
keybindings:
  universal:
    - key: pgup
      builtin: pageUp
    - key: pgdown
      builtin: pageDown
theme:
  ui:
    sectionsShowCount: true
    table:
      compact: false
      showSeparator: true
  colors:
    text:
      primary: '#f7f1ff'
      secondary: '#5ad4e6'
      inverted: '#282a36'
      faint: '#ffb86c'
      success: '#50fa7b'
      warning: '#ff5555'
      error: '#ff5555'
    background:
      selected: '#39386b'
    border:
      primary: '#383b5b'
      secondary: '#39386b'
      faint: '#2b2b40'
